# Generated by Django 6.0.2 on 2026-02-26 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('muscle_group', models.CharField(choices=[('chest', 'Грудные'), ('back', 'Спина'), ('legs', 'Ноги'), ('shoulders', 'Плечи'), ('biceps', 'Бицепс'), ('triceps', 'Трицепс'), ('abs', 'Пресс'), ('cardio', 'Кардио'), ('full_body', 'Все тело')], max_length=20, verbose_name='Группа мышц')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('workout_type', models.CharField(choices=[('strength', 'Силовая'), ('cardio', 'Кардио'), ('hiit', 'HIIT'), ('yoga', 'Йога'), ('crossfit', 'Кроссфит'), ('running', 'Бег'), ('swimming', 'Плавание'), ('cycling', 'Велосипед'), ('other', 'Другое')], max_length=20, verbose_name='Тип тренировки')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата тренировки')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('duration', models.DurationField(help_text='Например: 01:30:00', verbose_name='Длительность')),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сожжено калорий')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('feeling', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Оценка от 1 до 5', null=True, verbose_name='Самочувствие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('sets', models.PositiveSmallIntegerField(verbose_name='Подходы')),
                ('reps', models.CharField(help_text='Например: 12, 10, 8 или до отказа', max_length=50, verbose_name='Повторения')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Дистанция (км)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Заметки к подходу')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.workout')),
            ],
            options={
                'verbose_name': 'Упражнение в тренировке',
                'verbose_name_plural': 'Упражнения в тренировке',
                'ordering': ['order'],
            },
        ),
    ]
